api_platform:
  enable_re_doc: false
  mapping:
    paths: [ '%kernel.project_dir%/src/Entity' ]
  patch_formats:
    jsonld: [ 'application/ld+json' ]
    json: [ 'application/json' ]
  path_segment_name_generator: api_platform.path_segment_name_generator.dash
  swagger:
    versions: [ 3 ]
