api_platform:
  defaults:
    pagination_items_per_page: 15
  description: Application de gestion de la production de T-Concept
  enable_re_doc: false
  formats:
    jsonld: [ application/ld+json ]
    json: [ application/json ]
    multipart: [ multipart/form-data ]
    html: [ text/html ]
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'
  patch_formats:
    json: [ application/merge-patch+json ]
  path_segment_name_generator: api_platform.path_segment_name_generator.dash
  swagger:
    versions: [ 3 ]
  title: TConcept-GPAO
