doctrine:
  dbal:
    types:
      employee_current_place: App\Doctrine\DBAL\Types\Hr\Employee\CurrentPlaceType
      product_current_place: App\Doctrine\DBAL\Types\Project\Product\CurrentPlaceType
    url: '%env(resolve:DATABASE_URL)%'
    wrapper_class: App\Doctrine\DBAL\Connection
  orm:
    auto_generate_proxy_classes: true
    auto_mapping: true
    mappings:
      App:
        alias: App
        dir: '%kernel.project_dir%/src/Doctrine/Entity'
        is_bundle: false
        prefix: App\Doctrine\Entity
        type: attribute
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
