doctrine:
  dbal:
    types:
      char: App\Doctrine\DBAL\Types\CharType
      !php/const Doctrine\DBAL\Types\Types::SIMPLE_ARRAY: App\Doctrine\DBAL\Types\SimpleArrayType
      !php/const Doctrine\DBAL\Types\Types::TEXT: App\Doctrine\DBAL\Types\TextType
      employee_current_place: App\Doctrine\DBAL\Types\Hr\Employee\CurrentPlaceType
      engine_type: App\Doctrine\DBAL\Types\Production\Engine\EngineType
      notification_category: App\Doctrine\DBAL\Types\Hr\Employee\NotificationCategoryType
      product_current_place: App\Doctrine\DBAL\Types\Project\Product\CurrentPlaceType
      product_kind: App\Doctrine\DBAL\Types\Project\Product\KindType
      tinyint: App\Doctrine\DBAL\Types\Tinyint
    url: '%env(resolve:DATABASE_URL)%'
    wrapper_class: App\Doctrine\DBAL\Connection
  orm:
    auto_generate_proxy_classes: true
    auto_mapping: true
    dql:
      datetime_functions:
        now: App\Doctrine\DQL\Now
    mappings:
      App:
        alias: App
        dir: '%kernel.project_dir%/src/Entity'
        is_bundle: false
        prefix: App\Entity
        type: attribute
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        pool: doctrine.system_cache_pool
        type: pool
      result_cache_driver:
        pool: doctrine.result_cache_pool
        type: pool
  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system

when@test:
  doctrine:
    dbal:
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'
