doctrine:
  dbal:
    connections:
      default:
        driver: pdo_mysql
        mapping_types:
          enum: string
        profiling_collect_backtrace: true
        url: '%env(resolve:DATABASE_URL)%'
        wrapper_class: App\Doctrine\DBAL\Connection
      migrations:
        driver: pdo_mysql
        mapping_types:
          enum: string
        url: '%env(resolve:DATABASE_ROOT_URL)%'
    default_connection: default
    types:
      attribute: App\Doctrine\DBAL\Types\Purchase\Component\AttributeType
      bill_state: App\Doctrine\DBAL\Types\Embeddable\Accounting\BillStateType
      blocker_state: App\Doctrine\DBAL\Types\Embeddable\BlockerStateType
      char: App\Doctrine\DBAL\Types\CharType
      check: App\Doctrine\DBAL\Types\Quality\Reception\Check\CheckType
      check_kind: App\Doctrine\DBAL\Types\Quality\Reception\Check\KindType
      check_state: App\Doctrine\DBAL\Types\Embeddable\Quality\Reception\CheckStateType
      closer_state: App\Doctrine\DBAL\Types\Embeddable\CloserStateType
      component_manufacturing_operation_state: App\Doctrine\DBAL\Types\Embeddable\ComponentManufacturingOperationStateType
      copper: App\Doctrine\DBAL\Types\Embeddable\CopperType
      contact: App\Doctrine\DBAL\Types\Management\Society\ContactType
      customer_address: App\Doctrine\DBAL\Types\Selling\Customer\AddressType
      customer_state: App\Doctrine\DBAL\Types\Embeddable\Selling\Customer\CustomerStateType
      !php/const Doctrine\DBAL\Types\Types::SIMPLE_ARRAY: App\Doctrine\DBAL\Types\SimpleArrayType
      !php/const Doctrine\DBAL\Types\Types::TEXT: App\Doctrine\DBAL\Types\TextType
      employee_engine_state: App\Doctrine\DBAL\Types\Embeddable\EmployeeEngineStateType
      engine_event: App\Doctrine\DBAL\Types\Production\Engine\EventType
      engine: App\Doctrine\DBAL\Types\Production\Engine\EngineType
      event_state: App\Doctrine\DBAL\Types\Embeddable\EventStateType
      gender_place: App\Doctrine\DBAL\Types\Hr\Employee\GenderType
      item: App\Doctrine\DBAL\Types\ItemType
      manufacturing_order_state: App\Doctrine\DBAL\Types\Embeddable\Production\Manufacturing\OrderStateType
      notification_category: App\Doctrine\DBAL\Types\Hr\Employee\NotificationCategoryType
      printer_color: App\Doctrine\DBAL\Types\Management\PrinterColorType
      product_state: App\Doctrine\DBAL\Types\Embeddable\Project\Product\ProductStateType
      product_kind: App\Doctrine\DBAL\Types\Project\Product\KindType
      purchase_order_item_closer_state: App\Doctrine\DBAL\Types\Embeddable\Purchase\Order\CloserStateType
      purchase_order_item_state: App\Doctrine\DBAL\Types\Embeddable\Purchase\Order\ItemStateType
      receipt_state: App\Doctrine\DBAL\Types\Embeddable\Logistics\Order\ReceiptStateType
      selling_order_item_state: App\Doctrine\DBAL\Types\Embeddable\Selling\Order\SellingOrderItemStateType
      selling_order_state: App\Doctrine\DBAL\Types\Embeddable\Selling\Order\SellingOrderStateType
      situation_place: App\Doctrine\DBAL\Types\Hr\Employee\SituationType
      purchase_order_state: App\Doctrine\DBAL\Types\Embeddable\Purchase\Order\OrderStateType
      supplier_state: App\Doctrine\DBAL\Types\Embeddable\Purchase\Supplier\SupplierStateType
      tinyint: App\Doctrine\DBAL\Types\Tinyint
      vat_message_force: App\Doctrine\DBAL\Types\Management\VatMessageForce
      warehouse_families: App\Doctrine\DBAL\Types\Logistics\FamilyType
  orm:
    auto_generate_proxy_classes: true
    default_entity_manager: default
    entity_managers:
      default:
        connection: default
        dql:
          datetime_functions:
            now: App\Doctrine\DQL\Now
        mappings:
          App:
            alias: App
            dir: '%kernel.project_dir%/src/Entity'
            is_bundle: false
            prefix: App\Entity
            type: attribute
          Tree:
            alias: Gedmo
            dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity'
            prefix: Gedmo\Tree\Entity
            type: attribute
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
      migrations:
        connection: migrations
        dql:
          datetime_functions:
            now: App\Doctrine\DQL\Now
        mappings:
          App:
            alias: App
            dir: '%kernel.project_dir%/src/Entity'
            is_bundle: false
            prefix: App\Entity
            type: attribute
          Tree:
            alias: Gedmo
            dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity'
            prefix: Gedmo\Tree\Entity
            type: attribute
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        pool: doctrine.system_cache_pool
        type: pool
      result_cache_driver:
        pool: doctrine.result_cache_pool
        type: pool
  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system

when@test:
  doctrine:
    dbal:
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'
