# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  http_client:
    scoped_clients:
      couchdb.client:
        base_uri: '%env(resolve:COUCH_URL)%'
        headers:
          Content-Type: application/json

  http_method_override: false

  #esi: true
  #fragments: true
  php_errors:
    log: true

  secret: '%env(APP_SECRET)%'
  #csrf_protection: true

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    cookie_samesite: lax
    cookie_secure: auto
    handler_id: null
    storage_factory_id: session.storage.factory.native

when@test:
  framework:
    session:
      storage_factory_id: session.storage.factory.mock_file
    test: true
