monolog:
  channels:
    - deprecation

when@dev:
  monolog:
    handlers:
      console:
        channels: [ '!console', '!doctrine', '!event' ]
        process_psr_3_messages: false
        type: console
      main:
        channels: [ '!event' ]
        level: debug
        path: '%kernel.logs_dir%/%kernel.environment%.log'
        type: rotating_file
        max_files: 30

when@prod:
  monolog:
    handlers:
      console:
        channels: [ '!doctrine', '!event' ]
        process_psr_3_messages: false
        type: console
      deprecation:
        channels: [ deprecation ]
        path: php://stderr
        type: stream
      main:
        action_level: error
        buffer_size: 50
        excluded_http_codes: [ 404, 405 ]
        handler: nested
        type: fingers_crossed
      nested:
        level: debug
        path: '%kernel.logs_dir%/%kernel.environment%.log'
        type: stream

when@test:
  monolog:
    handlers:
      main:
        action_level: error
        channels: [ '!event' ]
        excluded_http_codes: [ 404, 405 ]
        handler: nested
        type: fingers_crossed
      nested:
        level: debug
        path: '%kernel.logs_dir%/%kernel.environment%.log'
        type: stream
