nelmio_cors:
  defaults:
    #allow_headers: [ Content-Type, Authorization ]
    allow_headers: [ '*' ]
    allow_methods: [ '*' ]
    #allow_methods: [ GET, OPTIONS, POST, PUT, PATCH, DELETE ]
    #allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
    allow_origin: [ '*' ]
    #expose_headers: [ Link ]
    expose_headers: [ '*' ]
    max_age: 3600
    origin_regex: true
  paths:
    '^/api/':
      allow_origin: [ '*' ]
      allow_headers: [ '*' ]
      allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE', 'PATCH','OPTIONS' ]
      max_age: 3600
    '^/': null
