security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    users_in_memory:   # Ajout du fournisseur 'users_in_memory'
      memory:
        users:
          user: { password: 'password', roles: ['ROLE_USER'] }
          admin: { password: 'password', roles: ['ROLE_ADMIN'] }
    app_user_provider:
      entity:
        class: App\Entity\Hr\Employee\Employee
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: users_in_memory
  access_control:
      - { path: ^/api, roles: PUBLIC_ACCESS }
      # - { path: ^/profile, roles: ROLE_USER }