vich_uploader:
    db_driver: orm

    mappings:
        attachment:
            uri_prefix: ~
            upload_destination: '%kernel.project_dir%/public'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
