when@dev:
  framework:
    profiler: { only_exceptions: false }
  web_profiler:
    intercept_redirects: false
    toolbar: true

when@test:
  framework:
    profiler: { collect: false }
  web_profiler:
    intercept_redirects: false
    toolbar: false
