components:
  schemas:
    Resource:
      description: 'Base d''une resource'
      properties:
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
      required:
        - '@id'
        - '@type'
      type: object
info:
  description: 'Application de gestion de la production de T-Concept'
  title: TConcept-GPAO
  version: 0.0.0
openapi: 3.0.3
paths: {}
