components:
  parameters:
    id:
      allowEmptyValue: false
      allowReserved: false
      deprecated: false
      description: ''
      example: 1
      explode: false
      in: path
      name: id
      required: true
      schema:
        type: integer
      style: simple
  requestBodies:
    Carrier-write:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Carrier-write'
      description: Transporteur.
      required: true
    Carrier-write-patch:
      content:
        application/merge-patch+json:
          schema:
            $ref: '#/components/schemas/Carrier-write'
      description: Transporteur.
      required: true
  responses:
    Carrier-read:
      content:
        application/ld+json:
          schema:
            $ref: '#/components/schemas/Carrier-read'
      description: Transporteur.
  schemas:
    Address-read:
      additionalProperties: false
      allOf:
        -
          $ref: '#/components/schemas/Address-write'
      description: Adresse.
      required:
        - address
        - address2
        - city
        - country
        - email
        - phoneNumber
        - zipCode
      type: object
    Address-write:
      additionalProperties: false
      description: Adresse.
      properties:
        address:
          description: Adresse
          example: '5 rue Alfred Nobel'
          externalDocs:
            url: 'https://schema.org/streetAddress'
          format: streetAddress
          maxLength: 50
          minLength: 10
          nullable: true
          readOnly: false
          title: Adresse
          type: string
        address2:
          description: 'Complément d''adresse'
          example: 'ZA La charrière'
          externalDocs:
            url: 'https://schema.org/streetAddress'
          format: streetAddress
          maxLength: 50
          minLength: 10
          nullable: true
          readOnly: false
          title: 'Complément d''adresse'
          type: string
        city:
          description: Ville
          example: Rioz
          externalDocs:
            url: 'https://schema.org/addressLocality'
          format: addressLocality
          maxLength: 50
          minLength: 3
          nullable: true
          readOnly: false
          title: Ville
          type: string
        country:
          default: FR
          description: Pays
          example: FR
          externalDocs:
            url: 'https://schema.org/addressLocality'
          format: addressLocality
          maxLength: 2
          minLength: 2
          nullable: false
          readOnly: false
          title: Pays
          type: string
        email:
          description: E-mail
          example: sales@tconcept.fr
          externalDocs:
            url: 'https://schema.org/email'
          format: email
          maxLength: 60
          minLength: 5
          nullable: true
          readOnly: false
          title: E-mail
          type: string
        phoneNumber:
          description: 'Numéro de téléphone'
          example: '03 84 91 99 84'
          externalDocs:
            url: 'https://schema.org/telephone'
          format: telephone
          maxLength: 20
          minLength: 10
          nullable: true
          readOnly: false
          title: 'Numéro de téléphone'
          type: string
        zipCode:
          description: 'Code postal'
          example: '70190'
          externalDocs:
            url: 'https://schema.org/postalCode'
          format: postalCode
          maxLength: 10
          minLength: 2
          nullable: true
          readOnly: false
          title: 'Code postal'
          type: string
      type: object
    Carrier-read:
      additionalProperties: false
      allOf:
        -
          $ref: '#/components/schemas/Carrier-write'
        -
          $ref: '#/components/schemas/Entity'
        -
          additionalProperties: false
          properties:
            address:
              $ref: '#/components/schemas/Address-read'
          type: object
      description: Transporteur.
      required:
        - address
      type: object
    Carrier-write:
      additionalProperties: false
      description: Transporteur.
      properties:
        address:
          $ref: '#/components/schemas/Address-write'
        name:
          description: Nom
          example: DHL
          externalDocs:
            url: 'https://schema.org/name'
          format: name
          maxLength: 50
          minLength: 3
          nullable: false
          readOnly: false
          title: Nom
          type: string
      required:
        - name
      type: object
    Entity:
      additionalProperties: false
      allOf:
        -
          $ref: '#/components/schemas/Resource'
        -
          additionalProperties: false
          properties:
            id:
              default: 1
              example: 1
              nullable: false
              readOnly: true
              type: integer
          type: object
      description: Entité.
      type: object
    Resource:
      additionalProperties: false
      description: 'Base d''une resource.'
      properties:
        '@context':
          nullable: true
          oneOf:
            -
              nullable: false
              type: string
            -
              additionalProperties: true
              nullable: false
              properties:
                '@vocab':
                  nullable: false
                  readOnly: true
                  type: string
                hydra:
                  enum: ['https://www.w3.org/ns/hydra/core']
                  nullable: false
                  readOnly: true
                  type: string
              required:
                - '@vocab'
                - hydra
              type: object
          readOnly: true
        '@id':
          nullable: false
          readOnly: true
          type: string
        '@type':
          nullable: false
          readOnly: true
          type: string
      required:
        - '@context'
        - '@id'
        - '@type'
      type: object
info:
  description: 'Application de gestion de la production de T-Concept'
  title: TConcept-GPAO
  version: 0.0.0
openapi: 3.0.3
paths:
  /api/carriers:
    get:
      deprecated: false
      description: 'Récupère les transporteurs'
      parameters:
        -
          allowEmptyValue: true
          allowReserved: false
          deprecated: false
          description: ''
          explode: false
          in: query
          name: address.address
          required: false
          schema:
            type: string
          style: form
        -
          allowEmptyValue: true
          allowReserved: false
          deprecated: false
          description: ''
          explode: false
          in: query
          name: address.address2
          required: false
          schema:
            type: string
          style: form
        -
          allowEmptyValue: true
          allowReserved: false
          deprecated: false
          description: ''
          explode: false
          in: query
          name: address.city
          required: false
          schema:
            type: string
          style: form
        -
          allowEmptyValue: true
          allowReserved: false
          deprecated: false
          description: ''
          explode: false
          in: query
          name: address.country
          required: false
          schema:
            type: string
          style: form
        -
          allowEmptyValue: true
          allowReserved: false
          deprecated: false
          description: ''
          explode: false
          in: query
          name: address.email
          required: false
          schema:
            type: string
          style: form
        -
          allowEmptyValue: true
          allowReserved: false
          deprecated: false
          description: ''
          explode: false
          in: query
          name: name
          required: false
          schema:
            type: string
          style: form
      responses:
        200:
          $ref: '#/components/responses/Carrier-read'
      summary: 'Récupère les transporteurs'
      tags:
        - Carrier
    post:
      deprecated: false
      description: 'Créer un transporteur'
      requestBody:
        $ref: '#/components/requestBodies/Carrier-write'
      responses:
        201:
          $ref: '#/components/responses/Carrier-read'
      summary: 'Créer un transporteur'
      tags:
        - Carrier
  '/api/carriers/{id}':
    delete:
      deprecated: false
      description: 'Supprime un transporteur'
      responses:
        204:
          $ref: '#/components/responses/Carrier-read'
      summary: 'Supprime un transporteur'
      tags:
        - Carrier
    parameters:
      -
        $ref: '#/components/parameters/id'
    patch:
      deprecated: false
      description: 'Modifie un transporteur'
      requestBody:
        $ref: '#/components/requestBodies/Carrier-write-patch'
      responses:
        200:
          $ref: '#/components/responses/Carrier-read'
      summary: 'Modifie un transporteur'
      tags:
        - Carrier
