components:
  schemas:
    Entity:
      additionalProperties: false
      allOf:
        -
          $ref: '#/components/schemas/Resource'
        -
          additionalProperties: false
          type: object
      type: object
    Resource:
      additionalProperties: false
      description: 'Base d''une resource'
      properties:
        '@context':
          oneOf:
            -
              type: string
            -
              additionalProperties: true
              properties:
                '@vocab':
                  readOnly: true
                  type: string
                hydra:
                  enum: ['http://www.w3.org/ns/hydra/core#']
                  readOnly: true
                  type: string
              required:
                - '@vocab'
                - hydra
              type: object
          readOnly: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
      required:
        - '@context'
        - '@id'
        - '@type'
      type: object
info:
  description: 'Application de gestion de la production de T-Concept'
  title: TConcept-GPAO
  version: 0.0.0
openapi: 3.0.3
paths: {  }
