openapi: 3.0.3
info:
  title: TConcept-GPAO
  description: 'Application de gestion de la production de T-Concept'
  version: 0.0.0
servers: []
paths: []
components:
  schemas:
    Carrier-read:
      properties: []
      required: []
    Carrier-write:
      properties: []
      required: []
    Color-read:
      properties: []
      required: []
    Color-write:
      properties: []
      required: []
    Currency-read:
      properties: []
      required: []
    Currency-write:
      properties: []
      required: []
    Employee-read:
      properties: []
      required: []
    EngineGroup-read:
      properties: []
      required: []
    EngineGroup-write:
      properties: []
      required: []
    Product-admin:
      properties: []
      required: []
    Product-clone:
      properties: []
      required: []
    Product-collection:
      properties: []
      required: []
    Product-create:
      properties: []
      required: []
    Product-logistics:
      properties: []
      required: []
    Product-main:
      properties: []
      required: []
    Product-production:
      properties: []
      required: []
    Product-project:
      properties: []
      required: []
    Product-read:
      properties: []
      required: []
    Product-write:
      properties: []
      required: []
    Resource:
      description: 'Base d''une resource'
      properties:
        '@context':
          oneOf:
            -
              type: string
            -
              additionalProperties: true
              properties:
                '@vocab':
                  type: string
                hydra:
                  enum: ['http://www.w3.org/ns/hydra/core#']
                  type: string
              required:
                - '@vocab'
                - hydra
              type: object
          readOnly: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
      required:
        - '@context'
        - '@id'
        - '@type'
      type: object
    'read:family':
      properties: []
      required: []
    'read:incoterms':
      properties: []
      required: []
    'read:invoice-time-due':
      properties: []
      required: []
    'read:name':
      properties: []
      required: []
    'read:out-trainer':
      properties: []
      required: []
    'read:time-slot':
      properties: []
      required: []
    'read:type':
      properties: []
      required: []
    'read:unit':
      properties: []
      required: []
    'write:family':
      properties: []
      required: []
    'write:incoterms':
      properties: []
      required: []
    'write:invoice-time-due':
      properties: []
      required: []
    'write:name':
      properties: []
      required: []
    'write:out-trainer':
      properties: []
      required: []
    'write:time-slot':
      properties: []
      required: []
    'write:type':
      properties: []
      required: []
    'write:unit':
      properties: []
      required: []
security: []
tags: []
