components:
  responses:
    400:
      description: Bad request
    401:
      description: Unauthorized
    405:
      description: Method Not Allowed
    500:
      description: Internal Server Error
  schemas:
    Address-read:
      allOf:
        - $ref: '#/components/schemas/Address-write'
      required:
        - address
        - address2
        - city
        - country
        - email
        - phoneNumber
        - zipCode
    Address-property-read:
      properties:
        address:
          $ref: '#/components/schemas/Address-read'
          description: Adresse
          title: Adresse
      required:
        - address
      type: object
    Address-property-write:
      properties:
        address:
          $ref: '#/components/schemas/Address-write'
          description: Adresse
          title: Adresse
      type: object
    Address-write:
      allOf:
        - $ref: '#/components/schemas/Resource'
        - properties:
            address:
              description: Adresse
              example: 5 rue Alfred Nobel
              externalDocs:
                url: http://schema.org/streetAddress
              format: streetAddress
              maxLength: 50
              minLength: 10
              nullable: true
              title: Adresse
              type: string
            address2:
              description: Complément d'adresse
              example: ZA La charrière
              externalDocs:
                url: http://schema.org/streetAddress
              format: streetAddress
              maxLength: 50
              minLength: 10
              nullable: true
              title: Complément d'adresse
              type: string
            city:
              description: Ville
              example: Rioz
              externalDocs:
                url: http://schema.org/addressLocality
              format: addressLocality
              maxLength: 50
              minLength: 3
              nullable: true
              title: Ville
              type: string
            country:
              description: Pays
              example: FR
              externalDocs:
                url: http://schema.org/addressLocality
              format: addressLocality
              maxLength: 2
              minLength: 2
              nullable: true
              title: Pays
              type: string
            email:
              description: E-mail
              example: sales@tconcept.fr
              externalDocs:
                url: http://schema.org/email
              format: email
              maxLength: 60
              minLength: 5
              nullable: true
              title: E-mail
              type: string
            phoneNumber:
              description: Numéro de téléphone
              example: 03 84 91 99 84
              externalDocs:
                url: http://schema.org/telephone
              format: telephone
              maxLength: 20
              minLength: 10
              nullable: true
              title: Numéro de téléphone
              type: string
            zipCode:
              description: Code postal
              example: 70190
              externalDocs:
                url: http://schema.org/postalCode
              format: postalCode
              maxLength: 10
              minLength: 2
              nullable: true
              title: Code postal
              type: string
          type: object
    Auth:
      description: Authentification
      properties:
        password:
          description: Mot de passe
          example: super
          externalDocs:
            url: https://schema.org/accessCode
          format: accessCode
          maxLength: 20
          minLength: 4
          title: Mot de passe
          type: string
        username:
          description: Identifiant
          example: super
          maxLength: 20
          minLength: 3
          type: string
      required:
        - password
        - username
      type: object
    Carrier-read:
      allOf:
        - $ref: '#/components/schemas/Address-property-read'
        - $ref: '#/components/schemas/Carrier-properties'
        - $ref: '#/components/schemas/Entity'
      description: Transporteur
    Carrier-properties:
      description: Transporteur
      properties:
        name:
          description: Nom
          example: DHL
          maxLength: 50
          minLength: 3
          title: Nom
          type: string
      required:
        - name
      type: object
    Carrier-write:
      allOf:
        - $ref: '#/components/schemas/Address-property-write'
        - $ref: '#/components/schemas/Carrier-properties'
        - $ref: '#/components/schemas/Entity'
      description: Transporteur
    Color-read:
      allOf:
        - $ref: '#/components/schemas/Color-write'
        - $ref: '#/components/schemas/Entity'
      description: Couleur
    Color-write:
      description: Couleur
      properties:
        name:
          description: Nom
          example: Gris
          maxLength: 20
          minLength: 3
          title: Nom
          type: string
        rgb:
          description: rgb
          example: '#848484'
          externalDocs:
            url: https://schema.org/color
          format: color
          maxLength: 7
          minLength: 7
          title: rgb
          type: string
      required:
        - name
        - rgb
      type: object
    ComponentFamily-read:
      allOf:
        - $ref: '#/components/schemas/ComponentFamily-write'
        - $ref: '#/components/schemas/Entity'
      description: Famille de composants
      required:
        - copperable
        - customsCode
        - file
        - parent
    ComponentFamily-write:
      description: Famille de composants
      properties:
        code:
          description: Code
          example: CAB
          maxLength: 3
          minLength: 3
          title: Code
          type: string
        copperable:
          description: Cuivré
          example: true
          title: Cuivré
          type: boolean
        customsCode:
          description: Code douanier
          example: 8544300089
          maxLength: 10
          minLength: 4
          nullable: true
          type: string
        file:
          description: Icône
          example: /uploads/component-families/1.jpg
          format: binary
          nullable: true
          title: Icône
          type: string
        name:
          description: Nom
          example: Câbles
          maxLength: 20
          minLength: 3
          title: Nom
          type: string
        parent:
          description: Famille parente
          example: /api/component-families/2
          format: iri-reference
          nullable: true
          title: Famille parente
          type: string
      required:
        - code
        - name
      type: object
    Employee:
      allOf:
        - $ref: '#/components/schemas/Entity'
        - properties:
            name:
              description: Nom
              example: Super
              maxLength: 30
              minLength: 3
              title: Nom
              type: string
            roles:
              description: Rôles
              example:
                - ROLE_USER
              items:
                type: string
              minItems: 1
              title: Rôles
              type: array
            token:
              description: Token
              example: 47e65f14b42a5398c1eea9125aaf93e44b1ddeb93ea2cca769ea897e0a285e4e7cfac21dee1a56396e15c1c5ee7c8d4e0bf692c83cda86a6462ad707
              maxLength: 120
              minLength: 120
              nullable: true
              readOnly: true
              title: Token
              type: string
            username:
              description: identifiant
              example: super
              maxLength: 20
              minLength: 3
              title: identifiant
              type: string
          required:
            - name
            - roles
            - token
            - username
          type: object
    Employee-CurrentPlace:
      description: Status
      enum:
        - blocked
        - disabled
        - enabled
        - warning
      example: blocked
      type: string
    EngineGroup-read:
      allOf:
        - $ref: '#/components/schemas/EngineGroup-write'
        - $ref: '#/components/schemas/Entity'
      description: Groupe d'équipements
      required:
        - safetyDevice
    EngineGroup-write:
      description: Groupe d'équipements
      properties:
        code:
          description: Code
          example: TA
          maxLength: 3
          minLength: 2
          title: Code
          type: string
        name:
          description: Nom
          example: Table d'assemblage
          maxLength: 35
          minLength: 3
          title: Nom
          type: string
        safetyDevice:
          description: Organe de sécurité
          example: true
          title: Organe de sécurité
          type: boolean
      required:
        - code
        - name
      type: object
    Entity:
      allOf:
        - $ref: '#/components/schemas/Resource'
        - description: Base d'une entité
          properties:
            id:
              description: id
              example: 1
              minimum: 1
              readOnly: true
              title: id
              type: integer
          required:
            - id
          type: object
    EventType-read:
      allOf:
        - $ref: '#/components/schemas/Entity'
        - $ref: '#/components/schemas/EventType-write'
      description: Type d'événements
      required:
        - toStatus
    EventType-write:
      description: Type d'événements
      properties:
        name:
          description: Nom
          example: ABSENCE
          maxLength: 30
          minLength: 3
          title: Nom
          type: string
        toStatus:
          allOf:
            - $ref: '#/components/schemas/Employee-CurrentPlace'
            - nullable: true
      required:
        - name
      type: object
    Incoterms-read:
      allOf:
        - $ref: '#/components/schemas/Entity'
        - $ref: '#/components/schemas/Incoterms-write'
      description: Incoterms
    Incoterms-write:
      description: Incoterms
      properties:
        code:
          description: Code
          example: DDP
          maxLength: 11
          minLength: 3
          title: Code
          type: string
        name:
          description: Nom
          example: Delivered Duty Paid
          maxLength: 50
          minLength: 3
          title: Nom
          type: string
      required:
        - code
        - name
      type: object
    InvoiceTimeDue-read:
      allOf:
        - $ref: '#/components/schemas/Entity'
        - $ref: '#/components/schemas/InvoiceTimeDue-write'
      description: Délai de paiement des factures
      required:
        - days
        - daysAfterEndOfMonth
        - endOfMonth
    InvoiceTimeDue-write:
      description: Délai de paiement des factures
      properties:
        days:
          description: Jours
          example: 30
          maximum: 255
          minimum: 0
          nullable: true
          title: Jours
          type: integer
        daysAfterEndOfMonth:
          description: Jours après la fin du mois
          example: 0
          maximum: 255
          minimum: 0
          nullable: true
          title: Jours après la fin du mois
          type: integer
        endOfMonth:
          description: Fin du mois
          example: true
          title: Fin du mois
          type: boolean
        name:
          description: Nom
          example: 30 jours fin de mois
          maxLength: 30
          minLength: 3
          title: Nom
          type: string
      required:
        - name
      type: object
    Notification:
      description: Notification
      properties:
        category:
          description: Catégorie
          nullable: true
          title: Catégorie
          type: string
        createdAt:
          default: CURRENT_TIMESTAMP
          example: CURRENT_TIMESTAMP
          format: date-time
          type: string
        read:
          type: boolean
        subject:
          nullable: true
          type: string
        user:
          format: iri-reference
          type: string
      required:
        - category
      type: object
    Resource:
      description: Base d'une resource
      properties:
        '@context':
          oneOf:
            - type: string
            - additionalProperties: true
              properties:
                '@vocab':
                  type: string
                hydra:
                  enum: [ 'http://www.w3.org/ns/hydra/core#' ]
                  type: string
              required:
                - '@vocab'
                - hydra
              type: object
          readOnly: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
      required:
        - '@context'
        - '@id'
        - '@type'
      type: object
info:
  description: Application de gestion de la production de T-Concept
  title: TConcept-GPAO
  version: 0.0.0
paths: { }
openapi: 3.0.3
