services:
  app.filter.search_filter:
    abstract: true
    arguments:
      $managerRegistry: '@doctrine'
      $iriConverter: '@api_platform.iri_converter'
      $propertyAccessor: '@api_platform.property_accessor'
      $logger: '@?logger'
      $identifiersExtractor: '@?api_platform.identifiers_extractor.cached'
      $nameConverter: '@?api_platform.name_converter'
    autoconfigure: false
    autowire: false
    class: App\Filter\SearchFilter
    lazy: false
    public: true
    shared: true
    synthetic: false
  App\Filter\SearchFilter:
    alias: app.filter.search_filter
  unit.numeric_filter:
    arguments: [ { base: ~ } ]
    parent: api_platform.doctrine.orm.numeric_filter
    tags: [ api_platform.filter ]
  unit.order_filter:
    arguments: [ { base: ~, code: ~, name: ~, parent.code: ~ } ]
    parent: api_platform.doctrine.orm.order_filter
    tags: [ api_platform.filter ]
  unit.search_filter:
    arguments:
      $properties: { code: exact, name: partial, parent: exact, type: exact }
    parent: app.filter.search_filter
    tags: [ api_platform.filter ]
