security:
  access_control:
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      custom_authenticators:
        - App\Security\ApiAuthenticator
      lazy: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto
  providers:
    users:
      entity:
        class: App\Entity\Hr\Employee\Employee
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        memory_cost: 10
        time_cost: 3
