security:
  access_control:
    - { methods: [ POST ], path: ^/api/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { methods: [ GET ], path: '^/api/docs.{_format}', roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/\w+, roles: IS_AUTHENTICATED_FULLY }
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    login:
      context: api
      custom_authenticators:
        - App\Security\ApiAuthenticator
      lazy: true
      methods: [ POST ]
      pattern: ^/api/login$
    main:
      context: api
      lazy: true
      logout:
        path: _api_/logout_post
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto
  providers:
    users:
      entity:
        class: App\Entity\Hr\Employee\Employee
  role_hierarchy: !php/const App\Doctrine\Type\Hr\Employee\Role::ROLE_HIERARCHY
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        memory_cost: 10
        time_cost: 3
