framework:
  workflows:
    product:
      audit_trail: '%wf_audit_trail%'
      initial_marking: '%place_draft%'
      marking_store: '%wf_marking_store%'
      places:
        - '%place_agreed%'          # Accepté
        - '%place_blocked%'         # Bloqué
        - '%place_disabled%'        # Inactif
        - '%place_draft%'           # Brouillon
        - '%place_to_validate%'     # À valider
        - '%place_under_exemption%' # Sous-dérogation
      supports:
        - App\Doctrine\Entity\Project\Product\Product
      transitions:
        '%tr_block%':
          from: [ '%place_agreed%', '%place_under_exemption%' ]
          to: '%place_blocked%'
        '%tr_disable%':
          from: [ '%place_agreed%', '%place_under_exemption%' ]
          to: '%place_disabled%'
        '%tr_partially_unlock%':
          from: '%place_blocked%'
          to: '%place_under_exemption%'
        '%tr_partially_validate%':
          from: [ '%place_agreed%', '%place_to_validate%' ]
          to: '%place_under_exemption%'
        '%tr_submit_validation%':
          from: '%place_draft%'
          to: '%place_to_validate%'
        '%tr_unlock%':
          from: '%place_blocked%'
          to: '%place_agreed%'
        '%tr_validate%':
          from: [ '%place_to_validate%', '%place_under_exemption%' ]
          to: '%place_agreed%'
