framework:
  workflows:
    customer_order_item:
      audit_trail: '%wf_audit_trail%'
      initial_marking: '%place_draft%'
      marking_store: '%wf_marking_store%'
      places:
        - '%place_agreed%'
        - '%place_blocked%'
        - '%place_disabled%'
        - '%place_draft%'
        - '%place_paid%'
        - '%place_partially_delivered%'
        - '%place_sent%'
      supports:
        - App\Entity\Selling\Order\Item
      transitions:
        '%tr_accept%':
          from: [ '%place_blocked%', '%place_draft%' ]
          to: '%place_agreed%'
        '%tr_bill%':
          from: '%place_sent%'
          to: '%place_paid%'
        '%tr_block%':
          from: [ '%place_agreed%', '%place_partially_delivered%' ]
          to: '%place_blocked%'
        '%tr_deliver%':
          from: [ '%place_agreed%', '%place_blocked%' ]
          to: '%place_partially_delivered%'
        '%tr_disable%':
          from: [ '%place_agreed%', '%place_draft%' ]
          to: '%place_disabled%'
        '%tr_send%':
          from: [ '%place_agreed%', '%place_partially_delivered%' ]
          to: '%place_sent%'
