framework:
  workflows:
    customer:
      audit_trail: '%wf_audit_trail%'
      initial_marking: '%place_draft%'
      marking_store: '%wf_marking_store%'
      places:
        - '%place_agreed%'          # Accepté
        - '%place_blocked%'         # Bloqué
        - '%place_disabled%'        # Inactif
        - '%place_draft%'           # Brouillon
      supports:
        - App\Entity\Selling\Customer\Customer
      transitions:
        '%tr_block%':
          from: '%place_agreed%'
          to: '%place_blocked%'
        '%tr_disable%':
          from: '%place_agreed%'
          to: '%place_disabled%'
        '%tr_unlock%':
          from: '%place_blocked%'
          to: '%place_agreed%'
        '%tr_validate%':
          from: '%place_draft%'
          to: '%place_agreed%'
