framework:
  workflows:
    manufacturing:
      audit_trail: '%wf_audit_trail%'
      initial_marking: '%place_draft%'
      marking_store: '%wf_marking_store%'
      places:
        - '%place_draft%'
        - '%place_ready_to_sent%'
        - '%place_sent%'
      supports:
        - App\Entity\Production\Manufacturing\DeliveryNote
      transitions:
        '%tr_send%':
          from: '%place_ready_to_sent%'
          to: '%place_sent%'
        '%tr_validate%':
          from: '%place_draft%'
          to: '%place_ready_to_sent%'
