framework:
  workflows:
    manufacturing_operation:
      audit_trail: '%wf_audit_trail%'
      initial_marking: '%place_draft%'
      marking_store: '%wf_marking_store%'
      places:
        - '%place_agreed%'
        - '%place_blocked%'
        - '%place_closed%'
        - '%place_draft%'
        - '%place_under_exemption%'
      supports:
        - App\Entity\Production\Manufacturing\Operation
      transitions:
        '%tr_accept%':
          from: '%place_draft%'
          to: '%place_agreed%'
        '%tr_block%':
          from: [ '%place_agreed%', '%place_under_exemption%', '%place_draft%' ]
          to: '%place_blocked%'
        '%tr_supervise%':
          from: [ '%place_agreed%', '%place_blocked%', '%place_draft%' ]
          to: '%place_under_exemption%'
        '%tr_validate%':
          from: [ '%place_agreed%', '%place_under_exemption%' ]
          to: '%place_closed%'
