# login:
#   methods: [ post ]
#   path: /api/login

# logout:
#   methods: [ post ]
#   path: /api/logout

# mobile.login:
#   methods: [ post ]
#   path: /api/mobile/login

app:
  controller: App\Controller\TemplateController
  defaults:
    template: base.html.twig
  methods: [ get ]
  path: /{req}
  requirements:
    req: .*
