login:
  methods: [ post ]
  path: /api/login

logout:
  methods: [ post ]
  path: /api/logout

app:
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: base.html.twig
  methods: [ get ]
  path: /{req}
  requirements:
    req: .*
