services:
  _defaults:
    autoconfigure: true
    autowire: true

  App\:
    exclude:
      - ../dev/Fixtures/
    resource: ../dev/

  App\Command\FixturesCommand:
    arguments:
      $configDir: '%kernel.project_dir%/fixtures/config'
      $jsonDir: '%kernel.project_dir%/fixtures/data'
      $jsonPrefix: exportjson_table_
