services:
  _defaults:
    autoconfigure: true
    autowire: true
    bind:
      $deleted_connecteur: '@monolog.logger.deleted_connecteur'

  App\:
    exclude:
      - ../src/Api/Resource/
      - ../src/Collection.php
      - ../src/Controller/
      - ../src/DependencyInjection/
      - ../src/Entity/
      - ../src/Filesystem/Directory.php
      - ../src/Kernel.php
      - ../src/Paginator.php
      #- ../src/Security/ApiRequest.php
      - ../src/Tests
    resource: ../src/

  App\Controller\:
    resource: ../src/Controller
    tags: [ controller.service_arguments ]

  App\DataProvider\Purchase\Component\AttributeDataProvider:
    arguments:
      $itemPerPage: '%api_platform.collection.pagination.items_per_page%'

  api_platform.openapi.factory:
    arguments:
      $filterLocator: '@api_platform.filter_locator'
      $formats: '%api_platform.formats%'
      $operationPathResolver: '@api_platform.operation_path_resolver'
      $subresourceOperationFactory: '@api_platform.subresource_operation_factory'
    autoconfigure: false
    class: App\OpenApi\OpenApiFactory

  App\Doctrine\ORM\Decorator\EntityManagerDecorator:
    autoconfigure: false
    decorates: doctrine.orm.default_entity_manager

  App\EventListener\DeserializeListener:
    autoconfigure: false
    decorates: api_platform.listener.request.deserialize
    tags:
      - event: kernel.request
        name: kernel.event_listener

  App\EventListener\Embeddable\MeasureListener:
    autoconfigure: false
    tags:
      - event: postLoad
        name: doctrine.event_listener

  App\EventListener\HttpKernel\ExceptionListener:
    arguments:
      $exceptionToStatus: '%api_platform.exception_to_status%'
    autoconfigure: false
    tags:
      - event: kernel.exception
        name: kernel.event_listener
        priority: 2

  App\Filesystem\FileManager:
    arguments:
      $dashGenerator: '@api_platform.path_segment_name_generator.dash'
      $dir: '%kernel.project_dir%/public'
    autoconfigure: false

  App\Filter\RelationFilter:
    arguments:
      $identifiersExtractor: '@api_platform.identifiers_extractor.cached'
      $iriConverter: '@api_platform.iri_converter'
      $logger: '@logger'
      $managerRegistry: '@doctrine'
      $nameConverter: '@api_platform.name_converter'
      $propertyAccessor: '@api_platform.property_accessor'
      $requestStack: null
    tags: [ api_platform.filter ]

  App\Migrations\Factory:
    autoconfigure: false
    arguments:
      $decorated: '@App\Migrations\Factory.inner'
    decorates: doctrine.migrations.migrations_factory

  App\OpenApi\SchemaFactory:
    arguments:
      $dashGenerator: '@api_platform.path_segment_name_generator.dash'
    autoconfigure: false
    decorates: api_platform.hydra.json_schema.schema_factory

  App\OpenApi\OpenApiNormalizer:
    autoconfigure: false
    decorates: api_platform.openapi.normalizer

  App\Serializer\ContextBuilderInterface:
    autoconfigure: false
    decorates: api_platform.serializer.context_builder

  Symfony\Component\Validator\Mapping\Factory\MetadataFactoryInterface: '@validator.mapping.class_metadata_factory'

  App\DataPersister\FileDataPersister:
    arguments:
      $em: '@doctrine.orm.entity_manager'  # Injecte l'EntityManager
      $fm: '@App\Filesystem\FileManager'      # Injecte votre service FileManager
      $requests: '@request_stack'          # Injecte le RequestStack
    tags: ['api_platform.data_persister']
  
  App\DataPersister\CompositeDataPersister:
    arguments:
      - [ '@App\DataPersister\FileDataPersister', '@App\DataPersister\Hr\Employee\EmployeePostDataPersister' ]
    tags: ['api_platform.data_persister']