services:
  _defaults:
    autoconfigure: true
    autowire: true

  App\:
    exclude:
      - ../src/Api/Resource/
      - ../src/Controller/
      - ../src/DependencyInjection/
      - ../src/Entity/
      - ../src/Filesystem/Directory.php
      - ../src/Kernel.php
      - ../src/Security/ApiRequest.php
      - ../src/Tests
    resource: ../src/

  App\Controller\:
    resource: ../src/Controller
    tags: [ controller.service_arguments ]

  App\Controller\Logistics\Stock\StockController:
    arguments:
      $itemPerPage: '%api_platform.collection.pagination.items_per_page%'
    tags: [ controller.service_arguments ]

  App\DataProvider\Purchase\Order\ItemDataProvider:
    arguments:
      $itemPerPage: '%api_platform.collection.pagination.items_per_page%'

  api_platform.openapi.factory:
    arguments:
      $filterLocator: '@api_platform.filter_locator'
      $formats: '%api_platform.formats%'
      $operationPathResolver: '@api_platform.operation_path_resolver'
      $subresourceOperationFactory: '@api_platform.subresource_operation_factory'
    autoconfigure: false
    class: App\OpenApi\OpenApiFactory

  App\Doctrine\ORM\Decorator\EntityManagerDecorator:
    autoconfigure: false
    decorates: doctrine.orm.default_entity_manager

  App\EventListener\DeserializeListener:
    autoconfigure: false
    decorates: api_platform.listener.request.deserialize
    tags:
      - event: kernel.request
        name: kernel.event_listener

  App\EventListener\Embeddable\MeasureListener:
    autoconfigure: false
    tags:
      - event: postLoad
        name: doctrine.event_listener

  App\EventListener\Hr\Employee\NotificationListener:
    autoconfigure: false
    tags:
      - entity: App\Entity\Hr\Employee\Notification
        event: preRemove
        name: doctrine.orm.entity_listener

  App\EventListener\Production\Engine\EngineListener:
    autoconfigure: false
    tags:
      - entity: App\Entity\Production\Engine\Engine
        event: postPersist
        name: doctrine.orm.entity_listener

  App\EventListener\HttpKernel\ExceptionListener:
    arguments:
      $exceptionToStatus: '%api_platform.exception_to_status%'
    autoconfigure: false
    tags:
      - event: kernel.exception
        name: kernel.event_listener
        priority: 2

  App\EventListener\FamilyListener:
    autoconfigure: false
    tags:
      - entity: App\Entity\Family
        event: postLoad
        name: doctrine.orm.entity_listener

  App\EventListener\Purchase\Order\ItemListener:
    autoconfigure: false
    tags:
      - event: workflow.purchase_order_item.guard.deliver
        method: guardDeliver
        name: kernel.event_listener
      - event: workflow.purchase_order_item.completed.deliver
        method: onDeliver
        name: kernel.event_listener
      - event: workflow.purchase_order_item.guard.partially_deliver
        method: guardPartiallyDeliver
        name: kernel.event_listener

  App\EventListener\Purchase\Order\OrderListener:
    autoconfigure: false
    tags:
      - event: workflow.purchase_order.guard.deliver
        method: guardDeliver
        name: kernel.event_listener
      - event: workflow.purchase_order.guard.partially_deliver
        method: guardPartiallyDeliver
        name: kernel.event_listener

  App\EventListener\Security\LogoutListener:
    autoconfigure: false
    tags:
      - dispatcher: security.event_dispatcher.main
        event: Symfony\Component\Security\Http\Event\LogoutEvent
        name: kernel.event_listener

  App\EventListener\WriteListener:
    autoconfigure: false
    tags:
      - event: kernel.view
        method: onPost
        name: kernel.event_listener
        priority: !php/const ApiPlatform\Core\EventListener\EventPriorities::POST_WRITE

  App\Filesystem\FileManager:
    arguments:
      $dashGenerator: '@api_platform.path_segment_name_generator.dash'
      $dir: '%kernel.project_dir%/public'
    autoconfigure: false

  App\Filter\RelationFilter:
    arguments:
      $identifiersExtractor: '@api_platform.identifiers_extractor.cached'
      $iriConverter: '@api_platform.iri_converter'
      $logger: '@logger'
      $managerRegistry: '@doctrine'
      $nameConverter: '@api_platform.name_converter'
      $propertyAccessor: '@api_platform.property_accessor'
      $requestStack: null
    tags: [ api_platform.filter ]

  App\Migrations\Factory:
    autoconfigure: false
    arguments:
      $decorated: '@App\Migrations\Factory.inner'
    decorates: doctrine.migrations.migrations_factory

  App\OpenApi\SchemaFactory:
    arguments:
      $dashGenerator: '@api_platform.path_segment_name_generator.dash'
    autoconfigure: false
    decorates: api_platform.hydra.json_schema.schema_factory

  App\OpenApi\OpenApiNormalizer:
    autoconfigure: false
    decorates: api_platform.openapi.normalizer

  App\Serializer\ContextBuilderInterface:
    autoconfigure: false
    decorates: api_platform.serializer.context_builder

  stock.filter:
    arguments:
      $properties: { warehouse: ~ }
    autoconfigure: false
    autowire: false
    parent: App\Filter\RelationFilter
    tags: [ api_platform.filter ]

  stock.grouped_filter:
    arguments: [ { location: partial } ]
    autoconfigure: false
    autowire: false
    parent: api_platform.doctrine.orm.search_filter
    tags: [ api_platform.filter ]
