services:
  _defaults:
    autoconfigure: false
    autowire: true
  App\:
    autoconfigure: true
    exclude:
      - ../src/Collection.php
      - ../src/DependencyInjection/
      - ../src/Doctrine/Comparator.php
      - ../src/Doctrine/QueryBuilder.php
      - ../src/Doctrine/Type/
      - ../src/Entity/
      - ../src/Kernel.php
    resource: ../src/
  App\Migrations\Factory:
    decorates: doctrine.migrations.migrations_factory
  App\OpenApi\OpenApiFactory:
    decorates: api_platform.openapi.factory
  App\OpenApi\SchemaFactory:
    decorates: api_platform.json_schema.schema_factory
  App\Security\LogoutListener:
    tags:
      - dispatcher: security.event_dispatcher.main
        event: Symfony\Component\Security\Http\Event\LogoutEvent
        name: kernel.event_listener
