services:
  _defaults:
    autoconfigure: false
    autowire: true
  App\:
    autoconfigure: true
    exclude:
      - ../src/Collection.php
      - ../src/DependencyInjection/
      - ../src/Entity/
      - ../src/Kernel.php
    resource: ../src/
  App\Migrations\Factory:
    decorates: doctrine.migrations.migrations_factory
  App\OpenApi\OpenApiFactory:
    decorates: api_platform.openapi.factory
