services:
  _defaults:
    autoconfigure: true
    autowire: true
  App\:
    exclude:
      - ../src/DependencyInjection/
      - ../src/Entity/
      - ../src/Kernel.php
    resource: ../src/
  App\Migrations\Factory:
    autoconfigure: false
    decorates: doctrine.migrations.migrations_factory
